// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_hub.sql

package sqlc

import (
	"context"
)

const addAgentHubRoomAgent = `-- name: AddAgentHubRoomAgent :exec
INSERT OR IGNORE INTO agent_hub_room_agents (room_id, agent_id)
VALUES (?1, ?2)
`

type AddAgentHubRoomAgentParams struct {
	RoomID  string `json:"room_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) AddAgentHubRoomAgent(ctx context.Context, arg AddAgentHubRoomAgentParams) error {
	_, err := q.db.ExecContext(ctx, addAgentHubRoomAgent, arg.RoomID, arg.AgentID)
	return err
}

const createAgentHubRoom = `-- name: CreateAgentHubRoom :one
INSERT INTO agent_hub_rooms (
  id,
  owner_user_id,
  name,
  short_name,
  subtitle,
  summary,
  privacy,
  live,
  accent,
  status_class,
  attention,
  metadata,
  orchestrator_agent_id
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11,
  ?12
)
RETURNING id, owner_user_id, name, short_name, subtitle, summary, privacy, live, accent, status_class, attention, metadata, orchestrator_agent_id, created_at, updated_at
`

type CreateAgentHubRoomParams struct {
	OwnerUserID         string `json:"owner_user_id"`
	Name                string `json:"name"`
	ShortName           string `json:"short_name"`
	Subtitle            string `json:"subtitle"`
	Summary             string `json:"summary"`
	Privacy             string `json:"privacy"`
	Live                string `json:"live"`
	Accent              string `json:"accent"`
	StatusClass         string `json:"status_class"`
	Attention           int64  `json:"attention"`
	Metadata            string `json:"metadata"`
	OrchestratorAgentID string `json:"orchestrator_agent_id"`
}

func (q *Queries) CreateAgentHubRoom(ctx context.Context, arg CreateAgentHubRoomParams) (AgentHubRoom, error) {
	row := q.db.QueryRowContext(ctx, createAgentHubRoom,
		arg.OwnerUserID,
		arg.Name,
		arg.ShortName,
		arg.Subtitle,
		arg.Summary,
		arg.Privacy,
		arg.Live,
		arg.Accent,
		arg.StatusClass,
		arg.Attention,
		arg.Metadata,
		arg.OrchestratorAgentID,
	)
	var i AgentHubRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.ShortName,
		&i.Subtitle,
		&i.Summary,
		&i.Privacy,
		&i.Live,
		&i.Accent,
		&i.StatusClass,
		&i.Attention,
		&i.Metadata,
		&i.OrchestratorAgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentHubRoomMessage = `-- name: CreateAgentHubRoomMessage :one
INSERT INTO agent_hub_room_messages (
  id,
  room_id,
  sender_id,
  sender_type,
  sender_name,
  kind,
  title,
  body,
  metadata
)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING id, room_id, sender_id, sender_type, sender_name, kind, title, body, metadata, created_at
`

type CreateAgentHubRoomMessageParams struct {
	RoomID     string `json:"room_id"`
	SenderID   string `json:"sender_id"`
	SenderType string `json:"sender_type"`
	SenderName string `json:"sender_name"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Metadata   string `json:"metadata"`
}

func (q *Queries) CreateAgentHubRoomMessage(ctx context.Context, arg CreateAgentHubRoomMessageParams) (AgentHubRoomMessage, error) {
	row := q.db.QueryRowContext(ctx, createAgentHubRoomMessage,
		arg.RoomID,
		arg.SenderID,
		arg.SenderType,
		arg.SenderName,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Metadata,
	)
	var i AgentHubRoomMessage
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.SenderType,
		&i.SenderName,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentHubRoom = `-- name: DeleteAgentHubRoom :exec
DELETE FROM agent_hub_rooms
WHERE id = ?1
  AND owner_user_id = ?2
`

type DeleteAgentHubRoomParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) DeleteAgentHubRoom(ctx context.Context, arg DeleteAgentHubRoomParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentHubRoom, arg.ID, arg.OwnerUserID)
	return err
}

const deleteAgentHubRoomAgent = `-- name: DeleteAgentHubRoomAgent :exec
DELETE FROM agent_hub_room_agents
WHERE room_id = ?1
  AND agent_id = ?2
`

type DeleteAgentHubRoomAgentParams struct {
	RoomID  string `json:"room_id"`
	AgentID string `json:"agent_id"`
}

func (q *Queries) DeleteAgentHubRoomAgent(ctx context.Context, arg DeleteAgentHubRoomAgentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentHubRoomAgent, arg.RoomID, arg.AgentID)
	return err
}

const deleteAgentHubRoomMessage = `-- name: DeleteAgentHubRoomMessage :exec
DELETE FROM agent_hub_room_messages
WHERE agent_hub_room_messages.id = ?1
  AND agent_hub_room_messages.room_id = ?2
  AND agent_hub_room_messages.room_id IN (
    SELECT agent_hub_rooms.id FROM agent_hub_rooms WHERE agent_hub_rooms.owner_user_id = ?3
  )
`

type DeleteAgentHubRoomMessageParams struct {
	ID          string `json:"id"`
	RoomID      string `json:"room_id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) DeleteAgentHubRoomMessage(ctx context.Context, arg DeleteAgentHubRoomMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteAgentHubRoomMessage, arg.ID, arg.RoomID, arg.OwnerUserID)
	return err
}

const getAgentHubRoom = `-- name: GetAgentHubRoom :one
SELECT id, owner_user_id, name, short_name, subtitle, summary, privacy, live, accent, status_class, attention, metadata, orchestrator_agent_id, created_at, updated_at
FROM agent_hub_rooms
WHERE id = ?1
  AND owner_user_id = ?2
`

type GetAgentHubRoomParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) GetAgentHubRoom(ctx context.Context, arg GetAgentHubRoomParams) (AgentHubRoom, error) {
	row := q.db.QueryRowContext(ctx, getAgentHubRoom, arg.ID, arg.OwnerUserID)
	var i AgentHubRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.ShortName,
		&i.Subtitle,
		&i.Summary,
		&i.Privacy,
		&i.Live,
		&i.Accent,
		&i.StatusClass,
		&i.Attention,
		&i.Metadata,
		&i.OrchestratorAgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentHubRoomAgentsByOwner = `-- name: ListAgentHubRoomAgentsByOwner :many
SELECT a.room_id, a.agent_id, a.created_at
FROM agent_hub_room_agents a
JOIN agent_hub_rooms r ON r.id = a.room_id
WHERE r.owner_user_id = ?1
ORDER BY a.created_at ASC
`

func (q *Queries) ListAgentHubRoomAgentsByOwner(ctx context.Context, ownerUserID string) ([]AgentHubRoomAgent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHubRoomAgentsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHubRoomAgent
	for rows.Next() {
		var i AgentHubRoomAgent
		if err := rows.Scan(&i.RoomID, &i.AgentID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentHubRoomMessages = `-- name: ListAgentHubRoomMessages :many
SELECT m.id, m.room_id, m.sender_id, m.sender_type, m.sender_name, m.kind, m.title, m.body, m.metadata, m.created_at
FROM agent_hub_room_messages m
JOIN agent_hub_rooms r ON r.id = m.room_id
WHERE m.room_id = ?1
  AND r.owner_user_id = ?2
ORDER BY m.created_at ASC, m.id ASC
LIMIT ?3
`

type ListAgentHubRoomMessagesParams struct {
	RoomID      string `json:"room_id"`
	OwnerUserID string `json:"owner_user_id"`
	LimitCount  int64  `json:"limit_count"`
}

func (q *Queries) ListAgentHubRoomMessages(ctx context.Context, arg ListAgentHubRoomMessagesParams) ([]AgentHubRoomMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHubRoomMessages, arg.RoomID, arg.OwnerUserID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHubRoomMessage
	for rows.Next() {
		var i AgentHubRoomMessage
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.SenderType,
			&i.SenderName,
			&i.Kind,
			&i.Title,
			&i.Body,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentHubRooms = `-- name: ListAgentHubRooms :many
SELECT id, owner_user_id, name, short_name, subtitle, summary, privacy, live, accent, status_class, attention, metadata, orchestrator_agent_id, created_at, updated_at
FROM agent_hub_rooms
WHERE owner_user_id = ?1
ORDER BY updated_at DESC, created_at DESC
`

func (q *Queries) ListAgentHubRooms(ctx context.Context, ownerUserID string) ([]AgentHubRoom, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHubRooms, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentHubRoom
	for rows.Next() {
		var i AgentHubRoom
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.ShortName,
			&i.Subtitle,
			&i.Summary,
			&i.Privacy,
			&i.Live,
			&i.Accent,
			&i.StatusClass,
			&i.Attention,
			&i.Metadata,
			&i.OrchestratorAgentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentHubRoom = `-- name: UpdateAgentHubRoom :one
UPDATE agent_hub_rooms
SET name = ?1,
    short_name = ?2,
    subtitle = ?3,
    summary = ?4,
    privacy = ?5,
    live = ?6,
    accent = ?7,
    status_class = ?8,
    attention = ?9,
    metadata = ?10,
    orchestrator_agent_id = ?11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?12
  AND owner_user_id = ?13
RETURNING id, owner_user_id, name, short_name, subtitle, summary, privacy, live, accent, status_class, attention, metadata, orchestrator_agent_id, created_at, updated_at
`

type UpdateAgentHubRoomParams struct {
	Name                string `json:"name"`
	ShortName           string `json:"short_name"`
	Subtitle            string `json:"subtitle"`
	Summary             string `json:"summary"`
	Privacy             string `json:"privacy"`
	Live                string `json:"live"`
	Accent              string `json:"accent"`
	StatusClass         string `json:"status_class"`
	Attention           int64  `json:"attention"`
	Metadata            string `json:"metadata"`
	OrchestratorAgentID string `json:"orchestrator_agent_id"`
	ID                  string `json:"id"`
	OwnerUserID         string `json:"owner_user_id"`
}

func (q *Queries) UpdateAgentHubRoom(ctx context.Context, arg UpdateAgentHubRoomParams) (AgentHubRoom, error) {
	row := q.db.QueryRowContext(ctx, updateAgentHubRoom,
		arg.Name,
		arg.ShortName,
		arg.Subtitle,
		arg.Summary,
		arg.Privacy,
		arg.Live,
		arg.Accent,
		arg.StatusClass,
		arg.Attention,
		arg.Metadata,
		arg.OrchestratorAgentID,
		arg.ID,
		arg.OwnerUserID,
	)
	var i AgentHubRoom
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.ShortName,
		&i.Subtitle,
		&i.Summary,
		&i.Privacy,
		&i.Live,
		&i.Accent,
		&i.StatusClass,
		&i.Attention,
		&i.Metadata,
		&i.OrchestratorAgentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
