// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AgentHubRoom struct {
	ID                  string `json:"id"`
	OwnerUserID         string `json:"owner_user_id"`
	Name                string `json:"name"`
	ShortName           string `json:"short_name"`
	Subtitle            string `json:"subtitle"`
	Summary             string `json:"summary"`
	Privacy             string `json:"privacy"`
	Live                string `json:"live"`
	Accent              string `json:"accent"`
	StatusClass         string `json:"status_class"`
	Attention           int64  `json:"attention"`
	Metadata            string `json:"metadata"`
	OrchestratorAgentID string `json:"orchestrator_agent_id"`
	CreatedAt           string `json:"created_at"`
	UpdatedAt           string `json:"updated_at"`
}

type AgentHubRoomAgent struct {
	RoomID    string `json:"room_id"`
	AgentID   string `json:"agent_id"`
	CreatedAt string `json:"created_at"`
}

type AgentHubRoomMessage struct {
	ID         string `json:"id"`
	RoomID     string `json:"room_id"`
	SenderID   string `json:"sender_id"`
	SenderType string `json:"sender_type"`
	SenderName string `json:"sender_name"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Body       string `json:"body"`
	Metadata   string `json:"metadata"`
	CreatedAt  string `json:"created_at"`
}

type AgentHubRun struct {
	ID               string `json:"id"`
	RoomID           string `json:"room_id"`
	TriggerMessageID string `json:"trigger_message_id"`
	Objective        string `json:"objective"`
	Status           string `json:"status"`
	PlannerVersion   string `json:"planner_version"`
	CreatedBy        string `json:"created_by"`
	Metadata         string `json:"metadata"`
	CreatedAtMs      int64  `json:"created_at_ms"`
	UpdatedAtMs      int64  `json:"updated_at_ms"`
}

type AgentHubRunEvent struct {
	ID          string         `json:"id"`
	RunID       string         `json:"run_id"`
	TaskID      sql.NullString `json:"task_id"`
	Seq         int64          `json:"seq"`
	Type        string         `json:"type"`
	Payload     string         `json:"payload"`
	CreatedAtMs int64          `json:"created_at_ms"`
}

type AgentHubTask struct {
	ID              string         `json:"id"`
	RunID           string         `json:"run_id"`
	ParentTaskID    sql.NullString `json:"parent_task_id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	AssignedAgentID string         `json:"assigned_agent_id"`
	ProviderName    string         `json:"provider_name"`
	Priority        int64          `json:"priority"`
	Status          string         `json:"status"`
	TimeoutMs       int64          `json:"timeout_ms"`
	MaxRetries      int64          `json:"max_retries"`
	AttemptCount    int64          `json:"attempt_count"`
	IdempotencyKey  string         `json:"idempotency_key"`
	Metadata        string         `json:"metadata"`
	CreatedAtMs     int64          `json:"created_at_ms"`
	UpdatedAtMs     int64          `json:"updated_at_ms"`
}

type AgentHubTaskAttempt struct {
	ID             string        `json:"id"`
	RunID          string        `json:"run_id"`
	TaskID         string        `json:"task_id"`
	AttemptNo      int64         `json:"attempt_no"`
	ProviderName   string        `json:"provider_name"`
	AgentID        string        `json:"agent_id"`
	Status         string        `json:"status"`
	InputPayload   string        `json:"input_payload"`
	OutputPayload  string        `json:"output_payload"`
	ErrorMessage   string        `json:"error_message"`
	Retryable      int64         `json:"retryable"`
	StartedAtMs    int64         `json:"started_at_ms"`
	FinishedAtMs   sql.NullInt64 `json:"finished_at_ms"`
	IdempotencyKey string        `json:"idempotency_key"`
}

type AgentHubTaskDep struct {
	RunID           string `json:"run_id"`
	TaskID          string `json:"task_id"`
	DependsOnTaskID string `json:"depends_on_task_id"`
}

type Bot struct {
	ID                     string         `json:"id"`
	OwnerUserID            string         `json:"owner_user_id"`
	Type                   string         `json:"type"`
	DisplayName            sql.NullString `json:"display_name"`
	AvatarUrl              sql.NullString `json:"avatar_url"`
	Timezone               sql.NullString `json:"timezone"`
	IsActive               int64          `json:"is_active"`
	Status                 string         `json:"status"`
	AclDefaultEffect       string         `json:"acl_default_effect"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	DiscussProbeModelID    sql.NullString `json:"discuss_probe_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	DisplayEnabled         int64          `json:"display_enabled"`
	OverlayProvider        string         `json:"overlay_provider"`
	OverlayEnabled         int64          `json:"overlay_enabled"`
	OverlayConfig          string         `json:"overlay_config"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
	Framework              string         `json:"framework"`
	ProviderExt            string         `json:"provider_ext"`
}

type BotAclRule struct {
	ID                     string         `json:"id"`
	BotID                  string         `json:"bot_id"`
	Enabled                int64          `json:"enabled"`
	Description            sql.NullString `json:"description"`
	Action                 string         `json:"action"`
	Effect                 string         `json:"effect"`
	ChannelIdentityID      sql.NullString `json:"channel_identity_id"`
	SubjectChannelType     sql.NullString `json:"subject_channel_type"`
	SourceChannel          sql.NullString `json:"source_channel"`
	SourceConversationType sql.NullString `json:"source_conversation_type"`
	SourceConversationID   sql.NullString `json:"source_conversation_id"`
	SourceThreadID         sql.NullString `json:"source_thread_id"`
	CreatedByUserID        sql.NullString `json:"created_by_user_id"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type BotChannelConfig struct {
	ID               string         `json:"id"`
	BotID            string         `json:"bot_id"`
	ChannelType      string         `json:"channel_type"`
	Credentials      string         `json:"credentials"`
	ExternalIdentity sql.NullString `json:"external_identity"`
	SelfIdentity     string         `json:"self_identity"`
	Routing          string         `json:"routing"`
	Capabilities     string         `json:"capabilities"`
	Disabled         int64          `json:"disabled"`
	VerifiedAt       sql.NullString `json:"verified_at"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type BotChannelRoute struct {
	ID                     string         `json:"id"`
	BotID                  string         `json:"bot_id"`
	ChannelType            string         `json:"channel_type"`
	ChannelConfigID        sql.NullString `json:"channel_config_id"`
	ExternalConversationID string         `json:"external_conversation_id"`
	ExternalThreadID       sql.NullString `json:"external_thread_id"`
	ConversationType       sql.NullString `json:"conversation_type"`
	DefaultReplyTarget     sql.NullString `json:"default_reply_target"`
	ActiveSessionID        sql.NullString `json:"active_session_id"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type BotEmailBinding struct {
	ID              string `json:"id"`
	BotID           string `json:"bot_id"`
	EmailProviderID string `json:"email_provider_id"`
	EmailAddress    string `json:"email_address"`
	CanRead         int64  `json:"can_read"`
	CanWrite        int64  `json:"can_write"`
	CanDelete       int64  `json:"can_delete"`
	Config          string `json:"config"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type BotHeartbeatLog struct {
	ID           string         `json:"id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type BotHistoryMessage struct {
	ID                      string         `json:"id"`
	BotID                   string         `json:"bot_id"`
	SessionID               sql.NullString `json:"session_id"`
	SenderChannelIdentityID sql.NullString `json:"sender_channel_identity_id"`
	SenderAccountUserID     sql.NullString `json:"sender_account_user_id"`
	SourceMessageID         sql.NullString `json:"source_message_id"`
	SourceReplyToMessageID  sql.NullString `json:"source_reply_to_message_id"`
	Role                    string         `json:"role"`
	Content                 string         `json:"content"`
	Metadata                string         `json:"metadata"`
	Usage                   sql.NullString `json:"usage"`
	ModelID                 sql.NullString `json:"model_id"`
	CompactID               sql.NullString `json:"compact_id"`
	EventID                 sql.NullString `json:"event_id"`
	DisplayText             sql.NullString `json:"display_text"`
	CreatedAt               string         `json:"created_at"`
}

type BotHistoryMessageAsset struct {
	ID          string `json:"id"`
	MessageID   string `json:"message_id"`
	Role        string `json:"role"`
	Ordinal     int64  `json:"ordinal"`
	ContentHash string `json:"content_hash"`
	Name        string `json:"name"`
	Metadata    string `json:"metadata"`
	CreatedAt   string `json:"created_at"`
}

type BotHistoryMessageCompact struct {
	ID           string         `json:"id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	Summary      string         `json:"summary"`
	MessageCount int64          `json:"message_count"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type BotSession struct {
	ID              string         `json:"id"`
	BotID           string         `json:"bot_id"`
	RouteID         sql.NullString `json:"route_id"`
	ChannelType     sql.NullString `json:"channel_type"`
	Type            string         `json:"type"`
	Title           string         `json:"title"`
	Metadata        string         `json:"metadata"`
	ParentSessionID sql.NullString `json:"parent_session_id"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	DeletedAt       sql.NullString `json:"deleted_at"`
}

type BotSessionEvent struct {
	ID                      string         `json:"id"`
	BotID                   string         `json:"bot_id"`
	SessionID               string         `json:"session_id"`
	EventKind               string         `json:"event_kind"`
	EventData               string         `json:"event_data"`
	ExternalMessageID       sql.NullString `json:"external_message_id"`
	SenderChannelIdentityID sql.NullString `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64          `json:"received_at_ms"`
	CreatedAt               string         `json:"created_at"`
}

type BotStorageBinding struct {
	ID                string `json:"id"`
	BotID             string `json:"bot_id"`
	StorageProviderID string `json:"storage_provider_id"`
	BasePath          string `json:"base_path"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ChannelIdentity struct {
	ID               string         `json:"id"`
	ChannelType      string         `json:"channel_type"`
	ChannelSubjectID string         `json:"channel_subject_id"`
	DisplayName      sql.NullString `json:"display_name"`
	AvatarUrl        sql.NullString `json:"avatar_url"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Container struct {
	ID               string         `json:"id"`
	BotID            string         `json:"bot_id"`
	ContainerID      string         `json:"container_id"`
	ContainerName    string         `json:"container_name"`
	Image            string         `json:"image"`
	Status           string         `json:"status"`
	Namespace        string         `json:"namespace"`
	AutoStart        int64          `json:"auto_start"`
	ContainerPath    string         `json:"container_path"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
	LastStartedAt    sql.NullString `json:"last_started_at"`
	LastStoppedAt    sql.NullString `json:"last_stopped_at"`
	WorkspaceBackend string         `json:"workspace_backend"`
}

type ContainerVersion struct {
	ID          string `json:"id"`
	ContainerID string `json:"container_id"`
	SnapshotID  string `json:"snapshot_id"`
	Version     int64  `json:"version"`
	CreatedAt   string `json:"created_at"`
}

type EmailOauthToken struct {
	ID              string         `json:"id"`
	EmailProviderID string         `json:"email_provider_id"`
	EmailAddress    string         `json:"email_address"`
	AccessToken     string         `json:"access_token"`
	RefreshToken    string         `json:"refresh_token"`
	ExpiresAt       sql.NullString `json:"expires_at"`
	Scope           string         `json:"scope"`
	State           string         `json:"state"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type EmailOutbox struct {
	ID          string         `json:"id"`
	ProviderID  string         `json:"provider_id"`
	BotID       string         `json:"bot_id"`
	MessageID   string         `json:"message_id"`
	FromAddress string         `json:"from_address"`
	ToAddresses string         `json:"to_addresses"`
	Subject     string         `json:"subject"`
	BodyText    string         `json:"body_text"`
	BodyHtml    string         `json:"body_html"`
	Attachments string         `json:"attachments"`
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	SentAt      sql.NullString `json:"sent_at"`
	CreatedAt   string         `json:"created_at"`
}

type EmailProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type LifecycleEvent struct {
	ID          string `json:"id"`
	ContainerID string `json:"container_id"`
	EventType   string `json:"event_type"`
	Payload     string `json:"payload"`
	CreatedAt   string `json:"created_at"`
}

type McpConnection struct {
	ID            string         `json:"id"`
	BotID         string         `json:"bot_id"`
	Name          string         `json:"name"`
	Type          string         `json:"type"`
	Config        string         `json:"config"`
	IsActive      int64          `json:"is_active"`
	Status        string         `json:"status"`
	ToolsCache    string         `json:"tools_cache"`
	LastProbedAt  sql.NullString `json:"last_probed_at"`
	StatusMessage string         `json:"status_message"`
	AuthType      string         `json:"auth_type"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type McpOauthToken struct {
	ID                     string         `json:"id"`
	ConnectionID           string         `json:"connection_id"`
	ResourceMetadataUrl    string         `json:"resource_metadata_url"`
	AuthorizationServerUrl string         `json:"authorization_server_url"`
	AuthorizationEndpoint  string         `json:"authorization_endpoint"`
	TokenEndpoint          string         `json:"token_endpoint"`
	RegistrationEndpoint   string         `json:"registration_endpoint"`
	ScopesSupported        string         `json:"scopes_supported"`
	ClientID               string         `json:"client_id"`
	ClientSecret           string         `json:"client_secret"`
	AccessToken            string         `json:"access_token"`
	RefreshToken           string         `json:"refresh_token"`
	TokenType              string         `json:"token_type"`
	ExpiresAt              sql.NullString `json:"expires_at"`
	Scope                  string         `json:"scope"`
	PkceCodeVerifier       string         `json:"pkce_code_verifier"`
	StateParam             string         `json:"state_param"`
	ResourceUri            string         `json:"resource_uri"`
	RedirectUri            string         `json:"redirect_uri"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type MemoryProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	IsDefault int64  `json:"is_default"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Model struct {
	ID         string         `json:"id"`
	ModelID    string         `json:"model_id"`
	Name       sql.NullString `json:"name"`
	ProviderID string         `json:"provider_id"`
	Type       string         `json:"type"`
	Config     string         `json:"config"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ModelVariant struct {
	ID        string `json:"id"`
	ModelUuid string `json:"model_uuid"`
	VariantID string `json:"variant_id"`
	Weight    int64  `json:"weight"`
	Metadata  string `json:"metadata"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Provider struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	ClientType string         `json:"client_type"`
	Icon       sql.NullString `json:"icon"`
	Enable     int64          `json:"enable"`
	Config     string         `json:"config"`
	Metadata   string         `json:"metadata"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ProviderOauthToken struct {
	ID               string         `json:"id"`
	ProviderID       string         `json:"provider_id"`
	AccessToken      string         `json:"access_token"`
	RefreshToken     string         `json:"refresh_token"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	Scope            string         `json:"scope"`
	TokenType        string         `json:"token_type"`
	State            string         `json:"state"`
	PkceCodeVerifier string         `json:"pkce_code_verifier"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Schedule struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	Pattern      string        `json:"pattern"`
	MaxCalls     sql.NullInt64 `json:"max_calls"`
	CurrentCalls int64         `json:"current_calls"`
	CreatedAt    string        `json:"created_at"`
	UpdatedAt    string        `json:"updated_at"`
	Enabled      int64         `json:"enabled"`
	Command      string        `json:"command"`
	BotID        string        `json:"bot_id"`
}

type ScheduleLog struct {
	ID           string         `json:"id"`
	ScheduleID   string         `json:"schedule_id"`
	BotID        string         `json:"bot_id"`
	SessionID    sql.NullString `json:"session_id"`
	Status       string         `json:"status"`
	ResultText   string         `json:"result_text"`
	ErrorMessage string         `json:"error_message"`
	Usage        sql.NullString `json:"usage"`
	ModelID      sql.NullString `json:"model_id"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
}

type SearchProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	Enable    int64  `json:"enable"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Snapshot struct {
	ID                        string         `json:"id"`
	ContainerID               string         `json:"container_id"`
	RuntimeSnapshotName       string         `json:"runtime_snapshot_name"`
	DisplayName               sql.NullString `json:"display_name"`
	ParentRuntimeSnapshotName sql.NullString `json:"parent_runtime_snapshot_name"`
	Snapshotter               string         `json:"snapshotter"`
	Source                    string         `json:"source"`
	CreatedAt                 string         `json:"created_at"`
}

type StorageProvider struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ToolApprovalRequest struct {
	ID                           string         `json:"id"`
	BotID                        string         `json:"bot_id"`
	SessionID                    string         `json:"session_id"`
	RouteID                      sql.NullString `json:"route_id"`
	ChannelIdentityID            sql.NullString `json:"channel_identity_id"`
	ToolCallID                   string         `json:"tool_call_id"`
	ToolName                     string         `json:"tool_name"`
	ToolInput                    string         `json:"tool_input"`
	ShortID                      int64          `json:"short_id"`
	Status                       string         `json:"status"`
	DecisionReason               string         `json:"decision_reason"`
	RequestedByChannelIdentityID sql.NullString `json:"requested_by_channel_identity_id"`
	DecidedByChannelIdentityID   sql.NullString `json:"decided_by_channel_identity_id"`
	RequestedMessageID           sql.NullString `json:"requested_message_id"`
	PromptMessageID              sql.NullString `json:"prompt_message_id"`
	PromptExternalMessageID      string         `json:"prompt_external_message_id"`
	SourcePlatform               string         `json:"source_platform"`
	ReplyTarget                  string         `json:"reply_target"`
	ConversationType             string         `json:"conversation_type"`
	CreatedAt                    string         `json:"created_at"`
	DecidedAt                    sql.NullString `json:"decided_at"`
}

type User struct {
	ID           string         `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Role         string         `json:"role"`
	DisplayName  sql.NullString `json:"display_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	Timezone     string         `json:"timezone"`
	DataRoot     sql.NullString `json:"data_root"`
	LastLoginAt  sql.NullString `json:"last_login_at"`
	IsActive     int64          `json:"is_active"`
	Metadata     string         `json:"metadata"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type UserChannelBinding struct {
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
	ChannelType string `json:"channel_type"`
	Config      string `json:"config"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type UserProviderOauthToken struct {
	ID               string         `json:"id"`
	ProviderID       string         `json:"provider_id"`
	UserID           string         `json:"user_id"`
	AccessToken      string         `json:"access_token"`
	RefreshToken     string         `json:"refresh_token"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	Scope            string         `json:"scope"`
	TokenType        string         `json:"token_type"`
	State            string         `json:"state"`
	PkceCodeVerifier string         `json:"pkce_code_verifier"`
	Metadata         string         `json:"metadata"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}
